spring:
  application:
    name: windsurfers-weather
  datasource:
    url: jdbc:postgresql://localhost:5432/weatherdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: weather-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


weatherbit:
  api-key: "37008afca1134ffe889b7567b38d7977"
  api-url: "https://api.weatherbit.io/v2.0/forecast/daily"

logging:
  level:
    root: INFO
    com.example.windsurfers_weather: DEBUG
    org.springframework.web: WARN
    org.apache.kafka: WARN




